title = "Gitleaks Demo Config"

[extend]
# Extend the default gitleaks config
useDefault = true

[[rules]]
id = "demo-api-key"
description = "Detected a hardcoded DEMO API key"
regex = '''DEMO_SECRET_[A-Z0-9]{20,}'''
tags = ["demo", "api-key"]
