sonar.projectKey=shyamchauhansimform_actions_ex
sonar.organization=shyamchauhansimform

sonar.projectName=actions_ex
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*.yml,**/*.toml,**/.git/**

sonar.python.version=3
